version: '3'
services:
  db:
    build:
      context: .
      dockerfile: deploy/db/Dockerfile
    volumes:
      - postgres_db:/var/lib/postgresql/data
    env_file:
      - .env

  web:
    build:
      context: .
      dockerfile: deploy/web/Dockerfile
    ports:
      - "80:80"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_db:
#  sqlite_db:
