# Generated by Django 4.0.5 on 2022-06-21 12:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('type', models.CharField(choices=[('OFFER', 'Offer'), ('CATEGORY', 'Category')], max_length=20)),
                ('date', models.DateTimeField()),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.shopunit')),
            ],
        ),
    ]
