# Generated by Django 4.0.5 on 2022-06-21 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_alter_shopunit_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopunit',
            name='parent_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.shopunit'),
        ),
    ]
